proyecto_web/blog/urls.py
from django.urls import path,include
from blog import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [

    path("", views.blog, name="Blog"),
    path("categoria/<int:categoria_id>/", views.categoria, name="categoria"),

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

proyecto_web/carro/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name="carro"
urlpatterns = [
    path("agregar/<int:producto_id>/",views.agregar_producto,name="agregar"),
    path("eliminar/<int:producto_id>/",views.eliminar_producto,name="eliminar"),
    path("restar/<int:producto_id>/", views.restar_producto, name="restar"),
    path("limpiar/<int:producto_id>/", views.limpiar_producto, name="limpiar"),

]

proyecto_web/proyecto_web/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('servicios/', include('servicios.urls')),
    path('blog/', include('blog.urls')),
    path('contacto/', include('contacto.urls')),
    path('tienda/', include('tienda.urls')),
    path('carro/', include('carro.urls')),
    path('login/', include('autenticacion.urls')),
    path('',include('app_web.urls')),

]

proyecto_web/tienda/urls.py
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path("",views.tienda, name="Tienda"),

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

proyecto_web/carro/models.py
from django.db import models

# Create your models here.

proyecto_web/tienda/models.py
from django.db import models

# Create your models here.
class CategoriaProd(models.Model):
    nombre=models.CharField(max_length=50)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name="categoriaPropd"
        verbose_name_plural= "categoriasProd"
    def __str__(self):
        return self.nombre
    
class Producto(models.Model):
    nombre =models.CharField(max_length=50)
    categoria =models.ForeignKey(CategoriaProd,on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="tienda",null=True,blank=True)
    precio = models.FloatField()
    disponibilidad=models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta: 
        verbose_name="Producto"
        verbose_name_plural="Productos"

proyecto_web/carro/views.py
from django.shortcuts import render
from .carro import *
from tienda.models import *
from django.shortcuts import redirect
# Create your views here.

def agregar_producto (request,producto_id):
    carro=Carro(request)
    producto=Producto.objects.get(id=producto_id)
    carro.agregar(producto=producto)
    return redirect("Tienda")


def eliminar_producto(request, producto_id):
    carro = Carro(request)
    producto = Producto.objects.get(id=producto_id)
    carro.eliminar(producto=producto)
    return redirect("Tienda")

def restar_producto(request, producto_id):
    carro = Carro(request)
    producto = Producto.objects.get(id=producto_id)
    carro.restar_producto(producto=producto)
    return redirect("Tienda")


def limpiar_producto(request, producto_id):
    carro = Carro(request)
    carro.limpiar_carro()
    return redirect("Tienda")

proyecto_web/tienda/views.py
from itertools import product
from django.shortcuts import render
from .models import *
# Create your views here.


def tienda(request):
    producto = Producto.objects.all()
    return render(request, "tienda/tienda.html", {"productos": producto})

proyecto_web/tienda/templates/carro/widget.html
<table class="table table-bordered text-white">

<thead>
    <tr>
        <th colspan="3" class="text-center">
            Carro de Compra
        </th>
    </tr>
    <tr>
        <th>Producto</th>
        <th>Cantidad</th>
        <th>Suma</th>
    </tr>
</thead>
<tbody>
    {% if request.session.carro.items %}
{% for key, value in request.session.carro.items %}
<tr class="text-center">
    <td>{{value.nombre}}</td>
    <td>{{value.cantidad}}</td>
    <td class="d-block">
        <a href="{% url 'carro:agregar' value.producto_id %}" class="btn btn-sm btn-success">+</a>
        <a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-sm btn-success">-</a>
{{value.precio}} $
    </td>
</tr>
{% endfor %}
{% else %}

<tr>
    <td colspan="3" >
      <div class="alert alert-danger text-center w-100 m-0">
        Sin Productos
      </div>
    </td>
</tr>
    {% endif %}
</tbody>
<tfoot>
    <tr>
        <td colspan="3">
            Total: {{importe_total_carro}}
        </td>
    </tr>
</tfoot>
</table>